-- PostgreSQL schema baseline for KnowledgeSharingSystem
-- Source: final PostgreSQL baseline (single source of truth)

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'moderator', 'admin')),
    points INTEGER NOT NULL DEFAULT 0 CHECK (points >= 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_users_role ON users(role);
CREATE INDEX IF NOT EXISTS ix_users_points ON users(points);

CREATE TABLE IF NOT EXISTS categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS access_rules (
    rule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_points INTEGER NOT NULL CHECK (min_points >= 0),
    max_points INTEGER NOT NULL CHECK (max_points >= min_points),
    allowed_duration INTEGER NOT NULL CHECK (allowed_duration > 0),
    can_download BOOLEAN NOT NULL,
    can_upload BOOLEAN NOT NULL,
    description VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS documents (
    document_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id INTEGER NOT NULL REFERENCES users(user_id),
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    file_url VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'hidden')),
    original_file_name VARCHAR(255) NULL,
    file_size_bytes BIGINT NULL CHECK (file_size_bytes IS NULL OR (file_size_bytes > 0 AND file_size_bytes <= 15728640)),
    mime_type VARCHAR(100) NULL,
    file_hash VARCHAR(128) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_documents_owner_user_id ON documents(owner_user_id);
CREATE INDEX IF NOT EXISTS ix_documents_status ON documents(status);
CREATE INDEX IF NOT EXISTS ix_documents_created_at ON documents(created_at);

CREATE TABLE IF NOT EXISTS document_categories (
    document_id INTEGER NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL REFERENCES categories(category_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (document_id, category_id)
);

CREATE INDEX IF NOT EXISTS ix_document_categories_category_id ON document_categories(category_id);

CREATE TABLE IF NOT EXISTS comments (
    comment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    author_user_id INTEGER NOT NULL REFERENCES users(user_id),
    parent_comment_id INTEGER NULL REFERENCES comments(comment_id),
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'hidden')),
    reviewed_by_user_id INTEGER NULL REFERENCES users(user_id),
    review_note VARCHAR(255) NULL,
    reviewed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_comments_document_id ON comments(document_id);
CREATE INDEX IF NOT EXISTS ix_comments_author_user_id ON comments(author_user_id);
CREATE INDEX IF NOT EXISTS ix_comments_parent_comment_id_created_at ON comments(parent_comment_id, created_at ASC);
CREATE INDEX IF NOT EXISTS ix_comments_status_created_at ON comments(status, created_at ASC);

CREATE TABLE IF NOT EXISTS questions (
    question_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    asker_user_id INTEGER NOT NULL REFERENCES users(user_id),
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved', 'hidden')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_questions_document_id ON questions(document_id);
CREATE INDEX IF NOT EXISTS ix_questions_asker_user_id ON questions(asker_user_id);

CREATE TABLE IF NOT EXISTS answers (
    answer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id INTEGER NOT NULL REFERENCES questions(question_id) ON DELETE CASCADE,
    responder_user_id INTEGER NOT NULL REFERENCES users(user_id),
    content TEXT NOT NULL,
    is_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'hidden')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_answers_question_id ON answers(question_id);
CREATE INDEX IF NOT EXISTS ix_answers_responder_user_id ON answers(responder_user_id);

CREATE TABLE IF NOT EXISTS document_reviews (
    review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES documents(document_id),
    moderator_user_id INTEGER NOT NULL REFERENCES users(user_id),
    decision VARCHAR(20) NOT NULL CHECK (decision IN ('approved', 'rejected')),
    note VARCHAR(255) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_document_reviews_document_id ON document_reviews(document_id);
CREATE INDEX IF NOT EXISTS ix_document_reviews_moderator_user_id ON document_reviews(moderator_user_id);

CREATE TABLE IF NOT EXISTS reports (
    report_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id INTEGER NOT NULL REFERENCES users(user_id),
    document_id INTEGER NULL REFERENCES documents(document_id),
    comment_id INTEGER NULL REFERENCES comments(comment_id),
    question_id INTEGER NULL REFERENCES questions(question_id),
    answer_id INTEGER NULL REFERENCES answers(answer_id),
    reason VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'resolved', 'dismissed')),
    reviewed_by_user_id INTEGER NULL REFERENCES users(user_id),
    review_note VARCHAR(255) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ NULL,
    CHECK (num_nonnulls(document_id, comment_id, question_id, answer_id) = 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_reports_document_id_reporter_user_id
    ON reports(document_id, reporter_user_id)
    WHERE document_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_reports_reporter_user_id ON reports(reporter_user_id);
CREATE INDEX IF NOT EXISTS ix_reports_status ON reports(status);
CREATE INDEX IF NOT EXISTS ix_reports_reviewed_by_user_id ON reports(reviewed_by_user_id);
CREATE INDEX IF NOT EXISTS ix_reports_document_id_status_created_at ON reports(document_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS point_transactions (
    transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    transaction_type VARCHAR(50) NOT NULL CHECK (
        transaction_type IN (
            'upload_reward',
            'answer_reward',
            'moderation_reward',
            'download_cost',
            'penalty',
            'admin_adjustment',
            'comment_reward',
            'upvote_reward',
            'qa_rating_reward'
        )
    ),
    points INTEGER NOT NULL,
    description VARCHAR(255) NULL,
    document_id INTEGER NULL REFERENCES documents(document_id),
    answer_id INTEGER NULL REFERENCES answers(answer_id),
    review_id INTEGER NULL REFERENCES document_reviews(review_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_point_transactions_user_id_created_at
    ON point_transactions(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS download_history (
    download_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    downloader_user_id INTEGER NOT NULL REFERENCES users(user_id),
    document_id INTEGER NOT NULL REFERENCES documents(document_id),
    rule_id INTEGER NOT NULL REFERENCES access_rules(rule_id),
    access_start TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    access_end TIMESTAMPTZ NULL,
    allowed_duration INTEGER NOT NULL CHECK (allowed_duration > 0)
);

CREATE INDEX IF NOT EXISTS ix_download_history_user_document
    ON download_history(downloader_user_id, document_id);

CREATE TABLE IF NOT EXISTS user_activity_logs (
    log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    action VARCHAR(100) NOT NULL,
    target_type VARCHAR(50) NULL CHECK (
        target_type IS NULL OR target_type IN (
            'document',
            'comment',
            'question',
            'answer',
            'report',
            'download',
            'user'
        )
    ),
    target_id INTEGER NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_user_activity_logs_user_id_created_at
    ON user_activity_logs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_user_activity_logs_target
    ON user_activity_logs(target_type, target_id, created_at DESC);

CREATE TABLE IF NOT EXISTS notifications (
    notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    type VARCHAR(50) NOT NULL,
    title VARCHAR(150) NOT NULL,
    message VARCHAR(500) NOT NULL,
    metadata TEXT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    read_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_notifications_user_id_created_at
    ON notifications(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS registration_otps (
    otp_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    otp_code VARCHAR(10) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    used_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_registration_otps_email_created_at
    ON registration_otps(email, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_registration_otps_username_created_at
    ON registration_otps(username, created_at DESC);

CREATE TABLE IF NOT EXISTS document_reactions (
    reaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    reaction_type VARCHAR(20) NOT NULL CHECK (reaction_type IN ('like', 'dislike')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_document_reactions_document_id_user_id
    ON document_reactions(document_id, user_id);
CREATE INDEX IF NOT EXISTS ix_document_reactions_document_id_reaction_type
    ON document_reactions(document_id, reaction_type);

CREATE TABLE IF NOT EXISTS saved_documents (
    saved_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_saved_documents_document_id_user_id
    ON saved_documents(document_id, user_id);
CREATE INDEX IF NOT EXISTS ix_saved_documents_user_id_created_at
    ON saved_documents(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS question_sessions (
    session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    asker_user_id INTEGER NOT NULL REFERENCES users(user_id),
    owner_user_id INTEGER NOT NULL REFERENCES users(user_id),
    status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL,
    closed_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_question_sessions_asker_status_created_at
    ON question_sessions(asker_user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_question_sessions_owner_status_created_at
    ON question_sessions(owner_user_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS question_messages (
    message_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES question_sessions(session_id) ON DELETE CASCADE,
    sender_user_id INTEGER NOT NULL REFERENCES users(user_id),
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_question_messages_session_created_at
    ON question_messages(session_id, created_at ASC);

CREATE TABLE IF NOT EXISTS session_ratings (
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES question_sessions(session_id) ON DELETE CASCADE,
    asker_user_id INTEGER NOT NULL REFERENCES users(user_id),
    owner_user_id INTEGER NOT NULL REFERENCES users(user_id),
    stars SMALLINT NOT NULL CHECK (stars BETWEEN 1 AND 5),
    feedback VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (session_id, asker_user_id)
);

CREATE TABLE IF NOT EXISTS point_events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    event_type VARCHAR(50) NOT NULL CHECK (
        event_type IN (
            'upload_submitted',
            'upload_approved',
            'comment_given',
            'comment_received',
            'upvote_received',
            'document_viewed',
            'document_saved_by_other',
            'qa_session_rated'
        )
    ),
    points INTEGER NOT NULL CHECK (points BETWEEN -1000 AND 1000),
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    document_id INTEGER NULL REFERENCES documents(document_id) ON DELETE SET NULL,
    qa_session_id INTEGER NULL REFERENCES question_sessions(session_id),
    comment_id INTEGER NULL REFERENCES comments(comment_id),
    source_user_id INTEGER NULL REFERENCES users(user_id),
    metadata TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_by_user_id INTEGER NULL REFERENCES users(user_id),
    review_note VARCHAR(255) NULL,
    reviewed_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_point_events_status_created_at
    ON point_events(status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_point_events_user_id_created_at
    ON point_events(user_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_point_events_upload_submitted_user_document
    ON point_events(user_id, document_id, event_type)
    WHERE event_type = 'upload_submitted' AND document_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_point_events_upload_approved_user_document
    ON point_events(user_id, document_id, event_type)
    WHERE event_type = 'upload_approved' AND document_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_point_events_qa_session_rated_user_session
    ON point_events(user_id, qa_session_id, event_type)
    WHERE event_type = 'qa_session_rated' AND qa_session_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_point_events_comment_given_user_comment
    ON point_events(user_id, comment_id, event_type)
    WHERE event_type = 'comment_given' AND comment_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_point_events_comment_received_user_comment
    ON point_events(user_id, comment_id, event_type)
    WHERE event_type = 'comment_received' AND comment_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_point_events_upvote_received_user_document_source
    ON point_events(user_id, document_id, source_user_id, event_type)
    WHERE event_type = 'upvote_received'
      AND document_id IS NOT NULL
      AND source_user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_point_events_document_saved_user_document_source
    ON point_events(user_id, document_id, source_user_id, event_type)
    WHERE event_type = 'document_saved_by_other'
      AND document_id IS NOT NULL
      AND source_user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS document_access_logs (
    access_log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    viewer_user_id INTEGER NOT NULL REFERENCES users(user_id),
    access_type VARCHAR(20) NOT NULL CHECK (access_type IN ('full_view', 'download')),
    points_cost INTEGER NOT NULL DEFAULT 0 CHECK (points_cost >= 0),
    access_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_document_access_logs_user_document_date_type
    ON document_access_logs(viewer_user_id, document_id, access_date, access_type);
CREATE INDEX IF NOT EXISTS ix_document_access_logs_document_created_at
    ON document_access_logs(document_id, created_at DESC);

CREATE TABLE IF NOT EXISTS document_text_artifacts (
    artifact_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL UNIQUE REFERENCES documents(document_id) ON DELETE CASCADE,
    extracted_text TEXT NULL,
    normalized_text TEXT NULL,
    token_count INTEGER NOT NULL DEFAULT 0,
    extraction_method VARCHAR(30) NULL,
    extraction_warning VARCHAR(255) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_document_text_artifacts_token_count
    ON document_text_artifacts(token_count DESC);

CREATE TABLE IF NOT EXISTS document_plagiarism_reviews (
    plagiarism_review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    reviewed_by_user_id INTEGER NOT NULL REFERENCES users(user_id),
    decision VARCHAR(30) NOT NULL CHECK (decision IN ('approved_anyway', 'rejected_duplicate')),
    compared_document_id INTEGER NULL REFERENCES documents(document_id),
    plagiarism_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
    note VARCHAR(255) NULL,
    snapshot_metadata TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_document_plagiarism_reviews_document_created_at
    ON document_plagiarism_reviews(document_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_document_plagiarism_reviews_reviewer_created_at
    ON document_plagiarism_reviews(reviewed_by_user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS admin_action_logs (
    log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id INTEGER NOT NULL REFERENCES users(user_id),
    target_user_id INTEGER NOT NULL REFERENCES users(user_id),
    action_type VARCHAR(50) NOT NULL,
    old_value TEXT NULL,
    new_value TEXT NULL,
    note VARCHAR(255) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_admin_action_logs_actor_created_at
    ON admin_action_logs(actor_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_admin_action_logs_target_created_at
    ON admin_action_logs(target_user_id, created_at DESC);

COMMIT;
