-- Hidden Knowledge migration for KnowledgeSharingSystem
-- Adds moderator-curated document experience summaries and Q&A rating feedback.

BEGIN;

ALTER TABLE point_transactions
    DROP CONSTRAINT IF EXISTS point_transactions_transaction_type_check;

ALTER TABLE point_transactions
    ADD CONSTRAINT point_transactions_transaction_type_check CHECK (
        transaction_type IN (
            'upload_reward',
            'answer_reward',
            'moderation_reward',
            'download_cost',
            'penalty',
            'admin_adjustment',
            'comment_reward',
            'upvote_reward',
            'qa_rating_reward',
            'hidden_knowledge_reward'
        )
    );

CREATE TABLE IF NOT EXISTS qa_rating_feedback (
    feedback_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_id INTEGER NOT NULL UNIQUE REFERENCES session_ratings(rating_id) ON DELETE CASCADE,
    session_id INTEGER NOT NULL REFERENCES question_sessions(session_id) ON DELETE CASCADE,
    document_id INTEGER NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id),
    prompt_text VARCHAR(500) NOT NULL DEFAULT 'Vui long neu thac mac cua ban va cach giai quyet cua tac gia da dua ra, ban hai long voi cau tra loi chu?',
    question_summary TEXT NULL,
    author_solution TEXT NULL,
    satisfaction_note TEXT NULL,
    is_satisfied BOOLEAN NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_qa_rating_feedback_document_created_at
    ON qa_rating_feedback(document_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_qa_rating_feedback_session_id
    ON qa_rating_feedback(session_id);

ALTER TABLE point_events
    DROP CONSTRAINT IF EXISTS point_events_event_type_check;

ALTER TABLE point_events
    ADD CONSTRAINT point_events_event_type_check CHECK (
        event_type IN (
            'upload_submitted',
            'upload_approved',
            'comment_given',
            'comment_received',
            'upvote_received',
            'document_viewed',
            'document_saved_by_other',
            'qa_session_rated',
            'hidden_knowledge_contribution'
        )
    );

CREATE TABLE IF NOT EXISTS document_hidden_knowledge (
    knowledge_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL UNIQUE REFERENCES documents(document_id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    min_points_to_view INTEGER NOT NULL DEFAULT 61 CHECK (min_points_to_view >= 0),
    created_by_user_id INTEGER NOT NULL REFERENCES users(user_id),
    updated_by_user_id INTEGER NULL REFERENCES users(user_id),
    published_by_user_id INTEGER NULL REFERENCES users(user_id),
    export_file_url VARCHAR(500) NULL,
    export_mime_type VARCHAR(100) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL,
    published_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_document_hidden_knowledge_document_status
    ON document_hidden_knowledge(document_id, status);
CREATE INDEX IF NOT EXISTS ix_document_hidden_knowledge_status_published_at
    ON document_hidden_knowledge(status, published_at DESC);

CREATE TABLE IF NOT EXISTS hidden_knowledge_sources (
    source_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id INTEGER NOT NULL REFERENCES document_hidden_knowledge(knowledge_id) ON DELETE CASCADE,
    document_id INTEGER NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
    source_type VARCHAR(30) NOT NULL CHECK (source_type IN ('comment', 'question_message', 'qa_rating_feedback', 'manual')),
    comment_id INTEGER NULL REFERENCES comments(comment_id) ON DELETE CASCADE,
    message_id INTEGER NULL REFERENCES question_messages(message_id) ON DELETE CASCADE,
    feedback_id INTEGER NULL REFERENCES qa_rating_feedback(feedback_id) ON DELETE CASCADE,
    source_user_id INTEGER NULL REFERENCES users(user_id),
    added_by_user_id INTEGER NOT NULL REFERENCES users(user_id),
    extracted_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (
        (source_type = 'comment' AND comment_id IS NOT NULL AND message_id IS NULL AND feedback_id IS NULL)
        OR (source_type = 'question_message' AND message_id IS NOT NULL AND comment_id IS NULL AND feedback_id IS NULL)
        OR (source_type = 'qa_rating_feedback' AND feedback_id IS NOT NULL AND comment_id IS NULL AND message_id IS NULL)
        OR (source_type = 'manual' AND comment_id IS NULL AND message_id IS NULL AND feedback_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_hidden_knowledge_sources_knowledge_created_at
    ON hidden_knowledge_sources(knowledge_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_hidden_knowledge_sources_document_created_at
    ON hidden_knowledge_sources(document_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS ux_hidden_knowledge_sources_comment
    ON hidden_knowledge_sources(knowledge_id, comment_id)
    WHERE source_type = 'comment' AND comment_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_hidden_knowledge_sources_message
    ON hidden_knowledge_sources(knowledge_id, message_id)
    WHERE source_type = 'question_message' AND message_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_hidden_knowledge_sources_feedback
    ON hidden_knowledge_sources(knowledge_id, feedback_id)
    WHERE source_type = 'qa_rating_feedback' AND feedback_id IS NOT NULL;

COMMIT;
