const { getPool } = require('../../../utils/db');

let schemaReady = false;

const ensureDocumentRatingTable = async () => {
    if (schemaReady) return;

    const pool = getPool();
    await pool.query(`
        CREATE TABLE IF NOT EXISTS document_ratings (
            rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            document_id INTEGER NOT NULL REFERENCES documents(document_id) ON DELETE CASCADE,
            user_id INTEGER NOT NULL REFERENCES users(user_id),
            stars SMALLINT NOT NULL CHECK (stars BETWEEN 1 AND 5),
            review_text VARCHAR(1000) NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'hidden')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NULL,
            UNIQUE (document_id, user_id)
        );
    `);
    await pool.query(`
        CREATE INDEX IF NOT EXISTS ix_document_ratings_document_status_created_at
            ON document_ratings(document_id, status, created_at DESC);
    `);
    await pool.query(`
        CREATE INDEX IF NOT EXISTS ix_document_ratings_user_created_at
            ON document_ratings(user_id, created_at DESC);
    `);

    schemaReady = true;
};

const getDocumentForRating = async (documentId) => {
    await ensureDocumentRatingTable();
    const pool = getPool();
    const result = await pool.query(
        `
            SELECT
                d.document_id AS "documentId",
                d.title,
                d.owner_user_id AS "ownerUserId",
                d.status
            FROM documents d
            WHERE d.document_id = $1;
        `,
        [documentId]
    );

    return result.rows[0] || null;
};

const getDocumentRatingSummary = async ({ documentId, userId = null, includeHidden = false }) => {
    await ensureDocumentRatingTable();
    const pool = getPool();
    const activeStatusFilter = includeHidden ? '' : "AND dr.status = 'active'";

    const summaryResult = await pool.query(
        `
            SELECT
                COUNT(*)::INT AS "totalRatings",
                COALESCE(ROUND(AVG(dr.stars)::NUMERIC, 1), 0)::FLOAT AS "averageStars",
                COALESCE(SUM(CASE WHEN dr.stars = 5 THEN 1 ELSE 0 END), 0)::INT AS "star5",
                COALESCE(SUM(CASE WHEN dr.stars = 4 THEN 1 ELSE 0 END), 0)::INT AS "star4",
                COALESCE(SUM(CASE WHEN dr.stars = 3 THEN 1 ELSE 0 END), 0)::INT AS "star3",
                COALESCE(SUM(CASE WHEN dr.stars = 2 THEN 1 ELSE 0 END), 0)::INT AS "star2",
                COALESCE(SUM(CASE WHEN dr.stars = 1 THEN 1 ELSE 0 END), 0)::INT AS "star1"
            FROM document_ratings dr
            WHERE dr.document_id = $1
              ${activeStatusFilter};
        `,
        [documentId]
    );

    const recentResult = await pool.query(
        `
            SELECT
                dr.rating_id AS "ratingId",
                dr.document_id AS "documentId",
                dr.user_id AS "userId",
                u.name AS "userName",
                u.avatar_url AS "avatarUrl",
                dr.stars,
                dr.review_text AS "reviewText",
                dr.status,
                dr.created_at AS "createdAt",
                dr.updated_at AS "updatedAt"
            FROM document_ratings dr
            INNER JOIN users u ON u.user_id = dr.user_id
            WHERE dr.document_id = $1
              ${activeStatusFilter}
            ORDER BY COALESCE(dr.updated_at, dr.created_at) DESC, dr.rating_id DESC
            LIMIT 8;
        `,
        [documentId]
    );

    const myRatingResult = userId
        ? await pool.query(
              `
                SELECT
                    dr.rating_id AS "ratingId",
                    dr.document_id AS "documentId",
                    dr.user_id AS "userId",
                    dr.stars,
                    dr.review_text AS "reviewText",
                    dr.status,
                    dr.created_at AS "createdAt",
                    dr.updated_at AS "updatedAt"
                FROM document_ratings dr
                WHERE dr.document_id = $1
                  AND dr.user_id = $2
                LIMIT 1;
              `,
              [documentId, userId]
          )
        : { rows: [] };

    const summary = summaryResult.rows[0] || {};

    return {
        documentId,
        totalRatings: Number(summary.totalRatings || 0),
        averageStars: Number(summary.averageStars || 0),
        distribution: {
            5: Number(summary.star5 || 0),
            4: Number(summary.star4 || 0),
            3: Number(summary.star3 || 0),
            2: Number(summary.star2 || 0),
            1: Number(summary.star1 || 0),
        },
        myRating: myRatingResult.rows[0] || null,
        recentRatings: recentResult.rows,
    };
};

const upsertDocumentRating = async ({ documentId, userId, stars, reviewText }) => {
    await ensureDocumentRatingTable();
    const pool = getPool();
    const result = await pool.query(
        `
            INSERT INTO document_ratings (document_id, user_id, stars, review_text, status)
            VALUES ($1, $2, $3, $4, 'active')
            ON CONFLICT (document_id, user_id)
            DO UPDATE
            SET
                stars = EXCLUDED.stars,
                review_text = EXCLUDED.review_text,
                status = 'active',
                updated_at = NOW()
            RETURNING
                rating_id AS "ratingId",
                document_id AS "documentId",
                user_id AS "userId",
                stars,
                review_text AS "reviewText",
                status,
                created_at AS "createdAt",
                updated_at AS "updatedAt";
        `,
        [documentId, userId, stars, reviewText || null]
    );

    return result.rows[0] || null;
};

const deleteDocumentRating = async ({ documentId, userId }) => {
    await ensureDocumentRatingTable();
    const pool = getPool();
    const result = await pool.query(
        `
            DELETE FROM document_ratings
            WHERE document_id = $1
              AND user_id = $2
            RETURNING rating_id AS "ratingId";
        `,
        [documentId, userId]
    );

    return result.rows[0] || null;
};

module.exports = {
    ensureDocumentRatingTable,
    getDocumentForRating,
    getDocumentRatingSummary,
    upsertDocumentRating,
    deleteDocumentRating,
};
